import React from "react";
import DiagramFrame from "./DiagramFrame";
import { Defs, Box, Arrow, Label, LaneTitle } from "./primitives";

type DiagramProps = { bleed?: boolean };

/* ------------------------------------------------------------------ */
/* Forecasting platform                                                */
/* ------------------------------------------------------------------ */

function ForecastingDiagram({ bleed }: DiagramProps) {
  return (
    <DiagramFrame
      bleed={bleed}
      title="Forecasting platform architecture: ingestion through to a served model"
      caption="Source data lands in Delta under Unity Catalog, features are generated by a versioned job, every training run is logged to MLflow, and only a candidate that clears the validation gate can be registered and promoted. Rollback is selecting the previous version."
      viewBox="0 0 900 320"
    >
      <Defs />
      <LaneTitle x={20} y={26}>
        INGEST
      </LaneTitle>
      <LaneTitle x={200} y={26}>
        TRAIN
      </LaneTitle>
      <LaneTitle x={520} y={26}>
        GOVERN
      </LaneTitle>
      <LaneTitle x={760} y={26}>
        SERVE
      </LaneTitle>

      <Box x={20} y={110} w={130} h={58} label="Source data" sub="Delta / UC" />
      <Box x={190} y={110} w={140} h={58} label="Feature job" sub="versioned PySpark" />
      <Box x={370} y={110} w={120} h={58} label="Training" sub="XGBoost" />
      <Box x={530} y={40} w={150} h={58} label="MLflow tracking" sub="params + metrics" />
      <Box
        x={530}
        y={110}
        w={150}
        h={58}
        label="Validation gate"
        sub="accuracy + slices"
        emphasis
      />
      <Box x={530} y={196} w={150} h={58} label="Model registry" sub="Dev → Prod" />
      <Box x={730} y={110} w={150} h={58} label="Model Serving" sub="REST endpoint" />
      <Box x={730} y={196} w={150} h={58} label="React app" sub="Databricks App" />

      <Arrow d="M 150 139 L 186 139" />
      <Arrow d="M 330 139 L 366 139" />
      <Arrow d="M 490 139 L 526 139" />
      <Arrow d="M 445 110 L 445 70 L 526 70" muted />
      <Arrow d="M 605 168 L 605 192" />
      <Arrow d="M 680 225 L 730 225" muted />
      <Arrow d="M 680 139 L 726 139" />
      <Arrow d="M 805 168 L 805 192" />

      <Label x={470} y={104} anchor="middle">
        log every run
      </Label>
      <Label x={618} y={186} anchor="middle">
        pass
      </Label>
      <Label x={705} y={218} anchor="middle">
        promote
      </Label>

      <g>
        <path
          d="M 528 226 C 470 268 470 268 445 268 L 445 172"
          fill="none"
          stroke="currentColor"
          strokeOpacity={0.35}
          strokeWidth={1.25}
          strokeDasharray="5 4"
          markerEnd="url(#arrowhead-muted)"
        />
        <Label x={470} y={286} anchor="middle">
          rollback = select previous version
        </Label>
      </g>
    </DiagramFrame>
  );
}

/* ------------------------------------------------------------------ */
/* Multi-model inference router                                        */
/* ------------------------------------------------------------------ */

function RouterDiagram({ bleed }: DiagramProps) {
  const consumers = [
    "REST",
    "Polling",
    "SSE",
    "WebSockets",
    "Databricks Jobs",
  ];
  return (
    <DiagramFrame
      bleed={bleed}
      title="Inference router: five integration patterns into one request contract"
      caption="Five very different consumers enter through one gateway and are normalised into a single internal shape. The pipeline is four ordered stages (validate, batch, cache, route), and every prediction persists to governed Delta tables, so results are queryable history rather than a fire-and-forget response."
      viewBox="0 0 900 340"
    >
      <Defs />
      <LaneTitle x={20} y={26}>
        CONSUMERS
      </LaneTitle>
      <LaneTitle x={300} y={26}>
        GATEWAY
      </LaneTitle>
      <LaneTitle x={640} y={26}>
        SERVING
      </LaneTitle>

      {consumers.map((c, i) => (
        <Box key={c} x={20} y={50 + i * 54} w={140} h={40} label={c} />
      ))}

      {consumers.map((_, i) => (
        <Arrow
          key={i}
          d={`M 160 ${70 + i * 54} C 220 ${70 + i * 54} 220 158 275 158`}
          muted
        />
      ))}

      <Box x={280} y={128} w={110} h={60} label="Validate" sub="one shape" emphasis />
      <Box x={400} y={128} w={100} h={60} label="Batch" sub="coalesce" emphasis />
      <Box x={510} y={128} w={100} h={60} label="Cache" sub="semantic key" emphasis />
      <Box x={620} y={128} w={90} h={60} label="Route" emphasis />

      <Arrow d="M 390 158 L 396 158" />
      <Arrow d="M 500 158 L 506 158" />
      <Arrow d="M 610 158 L 616 158" />

      <Box x={750} y={60} w={130} h={44} label="Model A" />
      <Box x={750} y={116} w={130} h={44} label="Model B" />
      <Box x={750} y={172} w={130} h={44} label="Model C" />

      <Arrow d="M 710 150 C 730 150 730 82 746 82" muted />
      <Arrow d="M 710 158 L 746 138" muted />
      <Arrow d="M 710 166 C 730 166 730 194 746 194" muted />

      <Box
        x={400}
        y={252}
        w={310}
        h={50}
        label="Unity Catalog Delta tables"
        sub="every prediction is queryable history"
      />
      <Arrow d="M 555 188 L 555 248" />
    </DiagramFrame>
  );
}

/* ------------------------------------------------------------------ */
/* Genie → Power BI                                                     */
/* ------------------------------------------------------------------ */

function GenieDiagram({ bleed }: DiagramProps) {
  return (
    <DiagramFrame
      bleed={bleed}
      title="From a natural-language question to a governed Power BI report"
      caption="The question becomes SQL inside Databricks Genie, so Unity Catalog governance is inherited rather than reimplemented. The result set is profiled, and a deterministic rules layer, not the model, chooses the visual. Output is a real TMDL/PBIR project someone can open and own."
      viewBox="0 0 900 260"
    >
      <Defs />
      <Box x={20} y={100} w={130} h={58} label="Question" sub="plain English" />
      <Box
        x={180}
        y={100}
        w={140}
        h={58}
        label="Databricks Genie"
        sub="governed SQL"
        emphasis
      />
      <Box x={350} y={100} w={130} h={58} label="Result profile" sub="shape + types" />
      <Box
        x={510}
        y={100}
        w={140}
        h={58}
        label="Visual rules"
        sub="deterministic"
        emphasis
      />
      <Box x={680} y={100} w={90} h={58} label="YAML" />
      <Box x={790} y={100} w={90} h={58} label="TMDL" sub="PBIR" />

      <Arrow d="M 150 129 L 176 129" />
      <Arrow d="M 320 129 L 346 129" />
      <Arrow d="M 480 129 L 506 129" />
      <Arrow d="M 650 129 L 676 129" />
      <Arrow d="M 770 129 L 786 129" />

      <Box
        x={180}
        y={22}
        w={140}
        h={40}
        label="Unity Catalog"
        sub="asker's permissions"
        dashed
      />
      <Arrow d="M 250 62 L 250 96" muted dashed />

      <Label x={415} y={190} anchor="middle">
        cardinality · types · time dimension · measures vs dimensions
      </Label>
      <Label x={835} y={190} anchor="middle">
        opens in Power BI
      </Label>
    </DiagramFrame>
  );
}

/* ------------------------------------------------------------------ */
/* Semantic model migration                                            */
/* ------------------------------------------------------------------ */

function MigrationDiagram({ bleed }: DiagramProps) {
  const stages = [
    { label: "Parse", sub: "TMDL in" },
    { label: "Translate", sub: "DAX to SQL", emphasis: true },
    { label: "Generate", sub: "metric view YAML" },
    { label: "Deploy", sub: "SQL API" },
    { label: "Validate", sub: "KPI parity", emphasis: true },
  ];
  return (
    <DiagramFrame
      bleed={bleed}
      title="Semantic model migration: TMDL to a governed Unity Catalog metric view"
      caption="A TMDL export is parsed into tables, measures and relationships; translation applies configurable, deterministic DAX-to-SQL rules with unsettled measures surfaced in review bundles; the generated metric view YAML deploys to Unity Catalog through the SQL Statement Execution API; and validation compares KPI results against the Power BI baseline before sign-off."
      viewBox="0 0 900 320"
    >
      <Defs />
      <LaneTitle x={20} y={26}>
        INPUT
      </LaneTitle>
      <LaneTitle x={230} y={26}>
        PIPELINE
      </LaneTitle>
      <LaneTitle x={620} y={26}>
        GOVERNED OUTPUT
      </LaneTitle>

      <Box
        x={20}
        y={110}
        w={150}
        h={58}
        label="Power BI TMDL"
        sub="semantic model export"
      />

      {stages.map((s, i) => (
        <Box
          key={s.label}
          x={210 + i * 122}
          y={110}
          w={110}
          h={58}
          label={s.label}
          sub={s.sub}
          emphasis={s.emphasis}
        />
      ))}

      <Arrow d="M 170 139 L 206 139" />
      {stages.slice(1).map((_, i) => (
        <Arrow key={i} d={`M ${318 + i * 122} 139 L ${328 + i * 122} 139`} />
      ))}

      <Label x={387} y={190} anchor="middle">
        flagged measures get a review bundle
      </Label>
      <Label x={738} y={186} anchor="end">
        parity vs Power BI baseline
      </Label>

      <Box
        x={620}
        y={200}
        w={260}
        h={44}
        label="Unity Catalog metric views"
        sub="governed, first-class objects"
        emphasis
      />
      <Arrow d="M 753 168 L 753 196" />

      <Box
        x={590}
        y={266}
        w={140}
        h={40}
        label="Genie / AI-BI"
        sub="NLQ over metrics"
      />
      <Box
        x={750}
        y={266}
        w={130}
        h={40}
        label="SQL + BI"
        sub="DirectQuery"
      />
      <Arrow d="M 700 244 L 665 262" muted />
      <Arrow d="M 810 244 L 815 262" muted />
    </DiagramFrame>
  );
}

/* ------------------------------------------------------------------ */
/* Agent Skills pipeline                                               */
/* ------------------------------------------------------------------ */

function SkillsDiagram({ bleed }: DiagramProps) {
  return (
    <DiagramFrame
      bleed={bleed}
      title="Nine Agent Skills composing into a Power BI Desktop Project"
      caption="An entry-point orchestrator, a source-agnostic connector, a four-stage build pipeline and two post-pipeline skills. Two human confirmation gates sit in the flow so the agent stops and asks rather than guessing a schema at scale."
      viewBox="0 0 900 300"
    >
      <Defs />
      <LaneTitle x={20} y={26}>
        ENTRY
      </LaneTitle>
      <LaneTitle x={250} y={26}>
        PIPELINE
      </LaneTitle>
      <LaneTitle x={720} y={26}>
        POST
      </LaneTitle>

      <Box
        x={20}
        y={112}
        w={150}
        h={58}
        label="orchestrator"
        sub="NLQ entry point"
        emphasis
      />
      <Box x={20} y={196} w={150} h={58} label="data-source" sub="→ data-model.json" />

      <Box x={230} y={112} w={130} h={58} label="semantic-mapper" sub="stage 1 · TMDL" />
      <Box x={375} y={112} w={130} h={58} label="visual-selector" sub="stage 2" />
      <Box x={520} y={112} w={130} h={58} label="visual-generator" sub="stage 3 · PBIR" />
      <Box x={665} y={112} w={130} h={58} label="project-packager" sub="stage 4 · validate" />

      <Box x={700} y={210} w={170} h={48} label="theme-branding" />
      <Box x={700} y={30} w={170} h={48} label="bi-dash-creator" />

      <Arrow d="M 170 141 L 226 141" />
      <Arrow d="M 95 196 L 95 174" muted />
      <Arrow d="M 360 141 L 371 141" />
      <Arrow d="M 505 141 L 516 141" />
      <Arrow d="M 650 141 L 661 141" />
      <Arrow d="M 780 112 L 780 82" muted />
      <Arrow d="M 780 170 L 780 206" muted />

      <g>
        <circle cx={200} cy={141} r={9} fill="var(--accent)" opacity={0.9} />
        <text
          x={200}
          y={145}
          textAnchor="middle"
          fontSize={10}
          fontWeight={700}
          fill="var(--accent-fg)"
        >
          1
        </text>
        <circle cx={200} cy={225} r={9} fill="var(--accent)" opacity={0.9} />
        <text
          x={200}
          y={229}
          textAnchor="middle"
          fontSize={10}
          fontWeight={700}
          fill="var(--accent-fg)"
        >
          2
        </text>
      </g>
      <Label x={20} y={284} anchor="start">
        1 · data-model confirmation gate
      </Label>
      <Label x={300} y={284} anchor="start">
        2 · scaffold confirmation gate
      </Label>
    </DiagramFrame>
  );
}

/* ------------------------------------------------------------------ */
/* OntoBricks: before / after                                           */
/* ------------------------------------------------------------------ */

function OntoBricksDiagram({ bleed }: DiagramProps) {
  return (
    <DiagramFrame
      bleed={bleed}
      title="Before and after: a blocking graph read on the shared event loop"
      caption="Before, a slow graph read executed directly on the single uvicorn event loop, so while it ran nothing else could, including health checks. After, blocking work runs on an auto-sized worker pool and every read carries a server-side bound, so an oversized query fails as one cancelled request instead of taking the process down."
      viewBox="0 0 900 340"
    >
      <Defs />

      <text
        x={20}
        y={26}
        fontFamily="'Fira Code', ui-monospace, monospace"
        fontSize={11}
        fontWeight={700}
        fill="currentColor"
        opacity={0.7}
      >
        BEFORE
      </text>
      <Box x={20} y={48} w={110} h={40} label="Graph Chat" />
      <Box x={20} y={104} w={110} h={40} label="Other users" dashed />
      <Box
        x={200}
        y={62}
        w={170}
        h={68}
        label="uvicorn event loop"
        sub="single-threaded"
      />
      <Box x={410} y={62} w={130} h={68} label="Graph read" sub="unbounded" />

      <Arrow d="M 130 68 L 196 82" muted />
      <Arrow d="M 130 124 L 196 110" muted />
      <Arrow d="M 370 96 L 406 96" />

      <text
        x={570}
        y={92}
        fontFamily="'Fira Code', ui-monospace, monospace"
        fontSize={12}
        fontWeight={700}
        fill="var(--accent)"
      >
        whole app frozen
      </text>
      <text
        x={570}
        y={110}
        fontFamily="'Fira Code', ui-monospace, monospace"
        fontSize={10}
        fill="currentColor"
        opacity={0.6}
      >
        until redeploy
      </text>

      <line
        x1={20}
        y1={168}
        x2={880}
        y2={168}
        stroke="currentColor"
        strokeOpacity={0.18}
        strokeDasharray="4 4"
      />

      <text
        x={20}
        y={198}
        fontFamily="'Fira Code', ui-monospace, monospace"
        fontSize={11}
        fontWeight={700}
        fill="var(--accent)"
      >
        AFTER
      </text>
      <Box x={20} y={220} w={110} h={40} label="Graph Chat" />
      <Box x={20} y={276} w={110} h={40} label="Other users" />
      <Box
        x={200}
        y={234}
        w={170}
        h={68}
        label="uvicorn event loop"
        sub="stays responsive"
        emphasis
      />
      <Box x={410} y={210} w={150} h={44} label="Worker pool" sub="auto-sized" emphasis />
      <Box x={410} y={272} w={150} h={44} label="Bounded read" sub="clamped timeout" emphasis />

      <Arrow d="M 130 240 L 196 254" muted />
      <Arrow d="M 130 296 L 196 282" muted />
      <Arrow d="M 370 258 L 406 236" />
      <Arrow d="M 370 278 L 406 292" />

      <text
        x={590}
        y={258}
        fontFamily="'Fira Code', ui-monospace, monospace"
        fontSize={12}
        fontWeight={700}
        fill="var(--accent)"
      >
        one request cancelled
      </text>
      <text
        x={590}
        y={276}
        fontFamily="'Fira Code', ui-monospace, monospace"
        fontSize={10}
        fill="currentColor"
        opacity={0.6}
      >
        everyone else unaffected
      </text>
    </DiagramFrame>
  );
}

/* ------------------------------------------------------------------ */
/* Medallion                                                           */
/* ------------------------------------------------------------------ */

function MedallionDiagram({ bleed }: DiagramProps) {
  return (
    <DiagramFrame
      bleed={bleed}
      title="Medallion architecture: Bronze, Silver and Gold"
      caption="Bronze stays faithful to the source so a source-side bug remains reproducible. Silver is where 'correct' gets defined: dedup, types, business rules. Gold pre-aggregates into the shapes a dashboard consumes, so query-time work stays trivial."
      viewBox="0 0 900 220"
    >
      <Defs />
      <Box x={20} y={80} w={130} h={60} label="Source" sub="market data" />
      <Box
        x={200}
        y={80}
        w={150}
        h={60}
        label="Bronze"
        sub="append-only, faithful"
      />
      <Box x={400} y={80} w={150} h={60} label="Silver" sub="dedup + types + rules" />
      <Box x={600} y={80} w={150} h={60} label="Gold" sub="KPI aggregates" emphasis />
      <Box x={800} y={80} w={80} h={60} label="Dashboard" />

      <Arrow d="M 150 110 L 196 110" />
      <Arrow d="M 350 110 L 396 110" />
      <Arrow d="M 550 110 L 596 110" />
      <Arrow d="M 750 110 L 796 110" />

      <Label x={275} y={168} anchor="middle">
        no cleaning here
      </Label>
      <Label x={475} y={168} anchor="middle">
        one place defines correctness
      </Label>
      <Label x={675} y={168} anchor="middle">
        cheap to query
      </Label>
    </DiagramFrame>
  );
}

/* ------------------------------------------------------------------ */

const registry: Record<string, React.ComponentType<DiagramProps>> = {
  forecasting: ForecastingDiagram,
  router: RouterDiagram,
  genie: GenieDiagram,
  migration: MigrationDiagram,
  skills: SkillsDiagram,
  ontobricks: OntoBricksDiagram,
  medallion: MedallionDiagram,
};

export default function Diagram({
  name,
  bleed,
}: {
  name: string;
  bleed?: boolean;
}) {
  const Component = registry[name];
  if (!Component) return null;
  return <Component bleed={bleed} />;
}
